name: login_with_bloc_api
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  aqueduct: ^4.0.0-b1
  mysql1: ^0.17.1
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  crypto: ^2.1.5
  jaguar_jwt: ^2.1.6

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1
  injectable_generator: ^0.4.1
  build_runner: ^1.10.0